---

# ---
# Copy configuration files
# ---

- name: configure cobbler setting
  template: src=./templates/settings.j2 dest=/etc/cobbler/settings

- name: configure cobbler dnsmasq
  template: src=./templates/dnsmasq.template.j2 dest=/etc/cobbler/dnsmasq.template

- name: configure cobbler modules
  template: src=./templates/modules.conf.j2 dest=/etc/cobbler/modules.conf

- name: configure cobbler dhcp
  template: src=./templates/dhcp.template.j2 dest=/etc/cobbler/dhcp.template

- name: configure cobbler pxe pxedefault.template
  template: src=./templates/pxedefault.template.j2 dest=/etc/cobbler/pxe/pxedefault.template

- name: configure cobbler pxe pxelocal.template
  template: src=./templates/pxelocal.template.j2 dest=/etc/cobbler/pxe/pxelocal.template

- name: configure cobbler pxe pxeprofile.template
  template: src=./templates/pxeprofile.template.j2 dest=/etc/cobbler/pxe/pxeprofile.template

- name: configure xinetd rsync
  template: src=./templates/rsync.j2 dest=/etc/xinetd.d/rsync

- name: configure xinetd tftp
  template: src=./templates/tftp.j2 dest=/etc/xinetd.d/tftp

- name: configure httpd cobbler-tftp.conf
  template: src=./templates/cobbler_tftp.conf.j2 dest=/etc/cobbler/cobbler_tftp.conf

- name: configure httpd cobbler-tftp.conf
  template: src=./templates/default.conf.j2 dest=/etc/dnsmasq.d/default.conf




